// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarterProject.Api.Data;

namespace StarterProject.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StarterProject.Api.Features.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Role");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@admin.com",
                            FirstName = "Seeded-Admin-FirstName",
                            LastName = "Seeded-Admin-LastName",
                            PasswordHash = new byte[] { 229, 200, 4, 247, 197, 7, 4, 213, 133, 199, 228, 100, 211, 148, 8, 186, 157, 36, 166, 40 },
                            PasswordSalt = new byte[] { 229, 173, 211, 167, 209, 178, 125, 29, 42, 75, 36, 28, 60, 191, 205, 35 },
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "delton_w@yahoo.com",
                            FirstName = "Delton",
                            LastName = "Watkins",
                            PasswordHash = new byte[] { 112, 142, 194, 124, 44, 203, 219, 67, 22, 207, 136, 107, 90, 243, 184, 213, 61, 115, 167, 170 },
                            PasswordSalt = new byte[] { 94, 109, 228, 224, 25, 29, 178, 179, 105, 161, 153, 224, 13, 99, 161, 27 },
                            Role = "Admin",
                            Username = "Delton94"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
